### ISSUE TITLE
CSS minification

### ISSUE THREAD

**Issue by ghost** [juliancwirko/meteor-bootstrap-postcss-test#1]
Does this example leave the CSS unminified? If so, does [cssnano, csso, or another postcss minifier](http://postcss.parts/tag/pack) work? I know the meteor build process complicates things. Considering implementing your recommended set up.

Thanks!

**Comment by juliancwirko** [comment]
Hi, this was just a test. Now you can use standard npm package with Meteor. I don't recommend using it that way because proper PostCSS integration in Meteor is almost impossible at the moment.
